"""Add expires_at to seat_reservations

Revision ID: fa0b96550ee1
Revises: 626fdcda02c2
Create Date: 2025-05-01 15:44:01.184303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa0b96550ee1'
down_revision: Union[str, None] = '626fdcda02c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat_reservations', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat_reservations', 'expires_at')
    # ### end Alembic commands ###
